[package]
name = "bosua-linux-gcp"
version = "0.1.0"
edition = "2021"

[dependencies]
bosua-lib = { path = "../bosua-lib", features = ["gcp", "http-server"] }
tokio.workspace = true
tracing.workspace = true
